name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  
  # Позволяет запускать вручную со вкладки Actions
  workflow_dispatch:

# --- ВОТ НОВОЕ ИСПРАВЛЕНИЕ ---
# Добавляем права на запись в репозиторий
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Генерируем змейку
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/snake.svg

      # Шаг 2: Загружаем в ветку 'output'
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
